import type { ShootInput } from './types';

/**
 * Seed test scenarios for Low Impact Pre-Check evaluation.
 * Each scenario has an expected output comment above it.
 */

/**
 * Expected: qualifies
 * Reasoning: 2 locations, 2 consecutive days, 18 crew, no activity flags, no location flags
 */
export const heroSilverLake: ShootInput = {
  projectName: 'Silver Lake Dialogue',
  firstFilmingDate: '2026-05-10',
  submissionDate: '2026-05-06',
  locationCount: 2,
  consecutiveFilmingDays: 2,
  isConsecutiveDays: true,
  onSetCount: 18,
  activitiesSelected: [],
  locationsSelected: ['residential', 'street'],
  hasSpecialEffects: false,
  hasGunfire: false,
  hasOfficerImpersonation: false,
  hasLaneClosures: false,
  hasTrafficControl: false,
  hasDrivingShots: false,
  hasAerialActivity: false,
  hasAnimalActivity: false,
  hasAmplifiedMusic: false,
  hasLargeLighting: false,
  hasGenerators: false,
  hasOpenFlames: false,
  hasPropaneHeaters: false,
  hasSmokeMachines: false,
  hasAlarmBypass: false,
  hasSmoking: false,
  hasPracticalStove: false,
  hasGrillingFoodPrep: false,
  hasStunts: false,
  hasLandscapeAlteration: false,
  hasSignRemoval: false,
  hasDiggingDrilling: false,
  hasNailingBolting: false,
  hasHeavyEquipmentOnGrass: false,
  hasCranes: false,
  locationTypes: [],
  fillingOutsideBusinessHours: false,
};

/**
 * Expected: doesNotQualify (with location-consolidation suggestion, tier 5)
 * Reasoning: 4 locations exceeds max of 3
 */
export const tooManyLocations: ShootInput = {
  projectName: 'Downtown Montage',
  firstFilmingDate: '2026-05-15',
  submissionDate: '2026-05-12',
  locationCount: 4,
  consecutiveFilmingDays: 2,
  isConsecutiveDays: true,
  onSetCount: 22,
  activitiesSelected: [],
  locationsSelected: ['street', 'park', 'storefront', 'alley'],
  hasSpecialEffects: false,
  hasGunfire: false,
  hasOfficerImpersonation: false,
  hasLaneClosures: false,
  hasTrafficControl: false,
  hasDrivingShots: false,
  hasAerialActivity: false,
  hasAnimalActivity: false,
  hasAmplifiedMusic: false,
  hasLargeLighting: false,
  hasGenerators: false,
  hasOpenFlames: false,
  hasPropaneHeaters: false,
  hasSmokeMachines: false,
  hasAlarmBypass: false,
  hasSmoking: false,
  hasPracticalStove: false,
  hasGrillingFoodPrep: false,
  hasStunts: false,
  hasLandscapeAlteration: false,
  hasSignRemoval: false,
  hasDiggingDrilling: false,
  hasNailingBolting: false,
  hasHeavyEquipmentOnGrass: false,
  hasCranes: false,
  locationTypes: [],
  fillingOutsideBusinessHours: false,
};

/**
 * Expected: doesNotQualify (with split-the-shoot suggestion, tier 1)
 * Reasoning: aerial activity (drone) disqualifies; but can be isolated to separate Standard day
 */
export const droneDisqualifier: ShootInput = {
  projectName: 'Rooftop Sequence with Aerial',
  firstFilmingDate: '2026-05-20',
  submissionDate: '2026-05-16',
  locationCount: 1,
  consecutiveFilmingDays: 3,
  isConsecutiveDays: true,
  onSetCount: 25,
  activitiesSelected: ['aerial'],
  locationsSelected: ['street'],
  hasSpecialEffects: false,
  hasGunfire: false,
  hasOfficerImpersonation: false,
  hasLaneClosures: false,
  hasTrafficControl: false,
  hasDrivingShots: false,
  hasAerialActivity: true,
  hasAnimalActivity: false,
  hasAmplifiedMusic: false,
  hasLargeLighting: false,
  hasGenerators: false,
  hasOpenFlames: false,
  hasPropaneHeaters: false,
  hasSmokeMachines: false,
  hasAlarmBypass: false,
  hasSmoking: false,
  hasPracticalStove: false,
  hasGrillingFoodPrep: false,
  hasStunts: false,
  hasLandscapeAlteration: false,
  hasSignRemoval: false,
  hasDiggingDrilling: false,
  hasNailingBolting: false,
  hasHeavyEquipmentOnGrass: false,
  hasCranes: false,
  locationTypes: [],
  fillingOutsideBusinessHours: false,
};

/**
 * Expected: needsReview (with rec-parks-verify suggestion, tier 2)
 * Reasoning: otherwise clean, but isRecParkProperty triggers review trigger
 */
export const recParksAmbiguity: ShootInput = {
  projectName: 'Griffith Park Narrative',
  firstFilmingDate: '2026-05-25',
  submissionDate: '2026-05-21',
  locationCount: 1,
  consecutiveFilmingDays: 1,
  isConsecutiveDays: true,
  onSetCount: 12,
  activitiesSelected: [],
  locationsSelected: ['park'],
  hasSpecialEffects: false,
  hasGunfire: false,
  hasOfficerImpersonation: false,
  hasLaneClosures: false,
  hasTrafficControl: false,
  hasDrivingShots: false,
  hasAerialActivity: false,
  hasAnimalActivity: false,
  hasAmplifiedMusic: false,
  hasLargeLighting: false,
  hasGenerators: false,
  hasOpenFlames: false,
  hasPropaneHeaters: false,
  hasSmokeMachines: false,
  hasAlarmBypass: false,
  hasSmoking: false,
  hasPracticalStove: false,
  hasGrillingFoodPrep: false,
  hasStunts: false,
  hasLandscapeAlteration: false,
  hasSignRemoval: false,
  hasDiggingDrilling: false,
  hasNailingBolting: false,
  hasHeavyEquipmentOnGrass: false,
  hasCranes: false,
  locationTypes: [],
  isRecParkProperty: true,
  fillingOutsideBusinessHours: false,
};
