// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/evaluate-low-impact-precheck.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";

// src/features/low-impact-precheck/rules.ts
var KB_URL = "https://info.filmla.com/general-information/low-impact-permit-pilot-program";
var ANNOUNCE_URL = "https://www.filmla.com/now-accepting-applications-for-lower-cost-low-impact-permits-in-city-of-los-angeles/";
var ACTIVITY_FLAGS = [
  {
    id: "act_special_effects",
    label: "No special effects requiring LAFD permit",
    category: "activity",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "act_gunfire",
    label: "No gunfire or brandishing of weapons",
    category: "activity",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "act_officer_impersonation",
    label: "No impersonating officers or emergency personnel",
    category: "activity",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "act_lane_closure",
    label: "No lane or sidewalk closures",
    category: "activity",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "act_traffic_control",
    label: "No traffic control or interference with the public right of way",
    category: "activity",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "act_driving_shots",
    label: "No driving shots",
    category: "activity",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "act_aerial_activity",
    label: "No aerial activity (UAS/drones, helicopters, planes)",
    category: "activity",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "act_animal_activity",
    label: "No animal activity",
    category: "activity",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "act_amplified_music",
    label: "No amplified music performance or playback",
    category: "activity",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "act_large_lighting",
    label: "No large lighting set ups or cranes",
    category: "activity",
    disqualifier: true,
    sourceUrl: KB_URL,
    // HEURISTIC, not in FilmLA KB — "large lighting set ups" is qualitative,
    // no wattage threshold published. Present to user as rough self-assessment.
    helpText: "Self-assess: Does your lighting setup require a crane, multiple HMIs >12kW, or a separate generator truck?"
  },
  {
    id: "act_generators",
    label: "No use of generators",
    category: "activity",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "act_open_flames",
    label: "No open flames",
    category: "activity",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "act_propane_heaters",
    label: "No use of propane heaters",
    category: "activity",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "act_smoke_machines",
    label: "No smoke machines",
    category: "activity",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "act_alarm_bypass",
    label: "No causing building alarm systems to be in test mode or bypassed",
    category: "activity",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "act_smoking",
    label: "No smoking",
    category: "activity",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "act_practical_stove",
    label: "No use of a practical stove, fireplace, grill, or any appliance requiring LAFD 315 permit",
    category: "activity",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "act_grilling_food_prep",
    label: "No grilling or food prep requiring heat sources",
    category: "activity",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "act_stunts",
    label: "No stunts",
    category: "activity",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  // The six rules below are scoped by FilmLA under "Limits Applying to
  // Recreation & Parks Locations" — not universal. evaluate.ts and formSchema.ts
  // gate them behind isRecParkProperty (F1 fix, verified 2026-07-23).
  {
    id: "act_landscape_alteration",
    label: "No alterations to landscape",
    category: "activity",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "act_sign_removal",
    label: "No removal or replacement of signs, park benches, or fencing",
    category: "activity",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "act_digging_drilling",
    label: "No digging, staking, or drilling into turf, rocks, trees, or asphalt",
    category: "activity",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "act_nailing_bolting",
    label: "No nailing or bolting into buildings, structures, or trees",
    category: "activity",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "act_heavy_equipment_grass",
    label: "No vehicles or heavy equipment on grass",
    category: "activity",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "act_cranes_jibs",
    label: "No condors, cranes, or jib arms",
    category: "activity",
    disqualifier: true,
    sourceUrl: KB_URL
  }
];
var REC_PARKS_SCOPED_ACTIVITY_IDS = [
  "act_landscape_alteration",
  "act_sign_removal",
  "act_digging_drilling",
  "act_nailing_bolting",
  "act_heavy_equipment_grass",
  "act_cranes_jibs"
];
var LOCATION_FLAGS = [
  {
    id: "loc_schools",
    label: "Schools, colleges, universities, churches, or hospitals (LAFD walkthroughs required)",
    category: "location",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "loc_city_buildings",
    label: "City-owned buildings or structures (Rec & Parks property exempt \u2014 see needs-review)",
    category: "location",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "loc_neighborhood_conditions",
    label: "Areas covered by Neighborhood Special Filming Conditions",
    category: "location",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "loc_rooftops",
    label: "Rooftops",
    category: "location",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "loc_hotels",
    label: "Hotels",
    category: "location",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "loc_interior_business",
    label: "Interior business locations open to the public",
    category: "location",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "loc_airports",
    label: "Airports",
    category: "location",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "loc_basements",
    label: "Basements",
    category: "location",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "loc_multistory_apartments",
    label: "Multistory apartments (4+ stories)",
    category: "location",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "loc_high_rises",
    label: "High rises (75+ ft)",
    category: "location",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "loc_brush",
    label: "Brush",
    category: "location",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "loc_harbor",
    label: "Harbor",
    category: "location",
    disqualifier: true,
    sourceUrl: KB_URL
  },
  {
    id: "loc_helipads",
    label: "Helipads or helicopter landings",
    category: "location",
    disqualifier: true,
    sourceUrl: KB_URL
  }
];
var REVIEW_TRIGGERS = [
  {
    id: "review_non_consecutive_days",
    label: "Non-consecutive filming days (gaps between days)",
    category: "review",
    disqualifier: false,
    sourceUrl: KB_URL,
    helpText: "KB is silent on gaps. Please verify with FilmLA whether breaks between filming days affect Low Impact eligibility."
  },
  {
    id: "review_large_lighting_self_assess",
    label: "Large lighting set ups (requires self-assessment)",
    category: "review",
    disqualifier: false,
    sourceUrl: KB_URL,
    helpText: "Qualitative only \u2014 no wattage threshold. Self-assess: Does your setup require a crane, multiple HMIs >12kW, or a separate generator truck?"
  },
  {
    id: "review_rec_parks_property",
    label: "Rec & Parks property (city-owned but potentially exempt)",
    category: "review",
    disqualifier: false,
    sourceUrl: KB_URL,
    helpText: "Rec & Parks property is noted as exempt in the pilot rules. Verify directly with FilmLA for your specific location."
  }
];
var THRESHOLDS = {
  maxLocations: 3,
  maxConsecutiveDays: 3,
  maxOnSetCount: 30
};
var DEADLINES = {
  minBusinessDays: 3,
  maxMonthsAhead: 1,
  // SOURCE AMBIGUITY: FilmLA says "up to six months" from Apr 27, 2026.
  // Oct 27 (exact) and Oct 31 (end-of-month) are both defensible.
  // Using Oct 31 as conservative upper bound.
  sunsetISO: "2026-10-31"
};
var FEE_MATH = {
  lowImpact: {
    application: 350,
    notificationPerLocation: 156,
    lafdSpotCheck: 0
  },
  standard: {
    application: 931,
    notificationPerLocation: 232,
    lafdSpotCheck: 287
  },
  savingsHeadline: "up to 58 percent less",
  savingsCitation: ANNOUNCE_URL
};

// src/features/low-impact-precheck/businessDays.ts
import Holidays from "npm:date-holidays@^3.27.0";
var hd = new Holidays("US", "CA");
function countBusinessDays(from, to) {
  let count = 0;
  const current = new Date(from);
  current.setHours(0, 0, 0, 0);
  const end = new Date(to);
  end.setHours(0, 0, 0, 0);
  current.setDate(current.getDate() + 1);
  while (current <= end) {
    const dayOfWeek = current.getDay();
    const isWeekend = dayOfWeek === 0 || dayOfWeek === 6;
    const isHoliday = hd.isHoliday(current);
    const isPublicHoliday = Array.isArray(isHoliday) ? isHoliday.some((h) => h.type === "public") : false;
    if (!isWeekend && !isPublicHoliday) {
      count++;
    }
    current.setDate(current.getDate() + 1);
  }
  return count;
}

// src/features/low-impact-precheck/evaluate.ts
var KB_URL2 = "https://info.filmla.com/general-information/low-impact-permit-pilot-program";
function findActivity(id) {
  const rule = ACTIVITY_FLAGS.find((r) => r.id === id);
  if (!rule) throw new Error(`Unknown activity rule: ${id}`);
  return rule;
}
function findLocation(id) {
  const rule = LOCATION_FLAGS.find((r) => r.id === id);
  if (!rule) throw new Error(`Unknown location rule: ${id}`);
  return rule;
}
function findReview(id) {
  const rule = REVIEW_TRIGGERS.find((r) => r.id === id);
  if (!rule) throw new Error(`Unknown review trigger: ${id}`);
  return rule;
}
function evaluate(input) {
  if (input.jurisdiction && input.jurisdiction !== "cityOfLA") {
    return {
      state: "notApplicable",
      blockers: [],
      reviewTriggers: [],
      timingNotices: [],
      appliedSuggestions: [],
      feeMath: { applicationFee: 0, notificationPerLocation: 0, lafdSpotCheck: 0, estimatedTotal: 0, savingsPercent: 0, standardTierEstimate: 0 }
    };
  }
  const blockers = [];
  const reviewTriggers = [];
  const timingNotices = [];
  if (input.hasSpecialEffects) blockers.push(findActivity("act_special_effects"));
  if (input.hasGunfire) blockers.push(findActivity("act_gunfire"));
  if (input.hasOfficerImpersonation) blockers.push(findActivity("act_officer_impersonation"));
  if (input.hasLaneClosures) blockers.push(findActivity("act_lane_closure"));
  if (input.hasTrafficControl) blockers.push(findActivity("act_traffic_control"));
  if (input.hasDrivingShots) blockers.push(findActivity("act_driving_shots"));
  if (input.hasAerialActivity) blockers.push(findActivity("act_aerial_activity"));
  if (input.hasAnimalActivity) blockers.push(findActivity("act_animal_activity"));
  if (input.hasAmplifiedMusic) blockers.push(findActivity("act_amplified_music"));
  if (input.hasLargeLighting) {
    if (input.hasLargeLightingAssessment === "yes") {
      blockers.push(findActivity("act_large_lighting"));
    } else if (input.hasLargeLightingAssessment === "unsure") {
      reviewTriggers.push(findReview("review_large_lighting_self_assess"));
    }
  }
  if (input.hasGenerators) blockers.push(findActivity("act_generators"));
  if (input.hasOpenFlames) blockers.push(findActivity("act_open_flames"));
  if (input.hasPropaneHeaters) blockers.push(findActivity("act_propane_heaters"));
  if (input.hasSmokeMachines) blockers.push(findActivity("act_smoke_machines"));
  if (input.hasAlarmBypass) blockers.push(findActivity("act_alarm_bypass"));
  if (input.hasSmoking) blockers.push(findActivity("act_smoking"));
  if (input.hasPracticalStove) blockers.push(findActivity("act_practical_stove"));
  if (input.hasGrillingFoodPrep) blockers.push(findActivity("act_grilling_food_prep"));
  if (input.hasStunts) blockers.push(findActivity("act_stunts"));
  if (input.isRecParkProperty) {
    const selected = input.recParksActivities || [];
    for (const id of REC_PARKS_SCOPED_ACTIVITY_IDS) {
      if (selected.includes(id)) blockers.push(findActivity(id));
    }
  }
  const locTypes = input.locationTypes || [];
  if (locTypes.includes("schools")) blockers.push(findLocation("loc_schools"));
  if (locTypes.includes("city_buildings") && !input.isRecParkProperty) {
    blockers.push(findLocation("loc_city_buildings"));
  }
  if (locTypes.includes("neighborhood_conditions")) blockers.push(findLocation("loc_neighborhood_conditions"));
  if (locTypes.includes("rooftops")) blockers.push(findLocation("loc_rooftops"));
  if (locTypes.includes("hotels")) blockers.push(findLocation("loc_hotels"));
  if (locTypes.includes("interior_business")) blockers.push(findLocation("loc_interior_business"));
  if (locTypes.includes("airports")) blockers.push(findLocation("loc_airports"));
  if (locTypes.includes("basements")) blockers.push(findLocation("loc_basements"));
  if (locTypes.includes("multistory_apartments")) blockers.push(findLocation("loc_multistory_apartments"));
  if (locTypes.includes("high_rises")) blockers.push(findLocation("loc_high_rises"));
  if (locTypes.includes("brush")) blockers.push(findLocation("loc_brush"));
  if (locTypes.includes("harbor")) blockers.push(findLocation("loc_harbor"));
  if (locTypes.includes("helipads")) blockers.push(findLocation("loc_helipads"));
  if (input.isRecParkProperty) {
    reviewTriggers.push(findReview("review_rec_parks_property"));
  }
  if (input.locationCount > THRESHOLDS.maxLocations) {
    blockers.push({
      id: "threshold_locations",
      label: `No more than ${THRESHOLDS.maxLocations} filming locations per project`,
      category: "threshold",
      disqualifier: true,
      sourceUrl: KB_URL2
    });
  }
  if (input.consecutiveFilmingDays > THRESHOLDS.maxConsecutiveDays) {
    blockers.push({
      id: "threshold_consecutive_days",
      label: `No more than ${THRESHOLDS.maxConsecutiveDays} consecutive filming days per project`,
      category: "threshold",
      disqualifier: true,
      sourceUrl: KB_URL2
    });
  }
  if (input.isConsecutiveDays === false && input.consecutiveFilmingDays <= THRESHOLDS.maxConsecutiveDays) {
    reviewTriggers.push(findReview("review_non_consecutive_days"));
  }
  if (input.onSetCount > THRESHOLDS.maxOnSetCount) {
    blockers.push({
      id: "threshold_on_set",
      label: `No more than ${THRESHOLDS.maxOnSetCount} total cast & crew physically on set`,
      category: "threshold",
      disqualifier: true,
      sourceUrl: KB_URL2
    });
  }
  if (input.filmingOutsideBusinessHours) {
    blockers.push({
      id: "hours_outside_standard",
      label: "Filming outside standard hours (7am\u201310pm weekdays, 9am\u201310pm weekends)",
      category: "hours",
      disqualifier: true,
      sourceUrl: KB_URL2
    });
  }
  const firstFilmDate = new Date(input.firstFilmingDate);
  const now = new Date(input.submissionDate);
  const businessDaysUntilShoot = countBusinessDays(now, firstFilmDate);
  if (businessDaysUntilShoot < DEADLINES.minBusinessDays) {
    blockers.push({
      id: "deadline_insufficient_notice",
      label: `Minimum ${DEADLINES.minBusinessDays} full business days notice required before first filming day (submit by 10am; weekends and CA holidays don't count)`,
      category: "deadline",
      disqualifier: true,
      sourceUrl: KB_URL2
    });
  }
  const daysUntilShoot = Math.floor((firstFilmDate.getTime() - now.getTime()) / (1e3 * 60 * 60 * 24));
  const monthsUntilShoot = daysUntilShoot / 30;
  if (monthsUntilShoot > DEADLINES.maxMonthsAhead) {
    timingNotices.push({
      id: "deadline_too_early",
      label: `Too early to submit \u2014 applications are accepted no more than ${DEADLINES.maxMonthsAhead} month before your first filming day. Apply closer to your filming date.`,
      category: "timing",
      disqualifier: false,
      sourceUrl: KB_URL2
    });
  }
  const sunsetDate = new Date(DEADLINES.sunsetISO);
  if (firstFilmDate > sunsetDate) {
    blockers.push({
      id: "deadline_pilot_sunset",
      label: "Filming must complete by October 31, 2026 (pilot program ends)",
      category: "deadline",
      disqualifier: true,
      sourceUrl: KB_URL2
    });
  }
  let state = "qualifies";
  if (blockers.length > 0) {
    state = "doesNotQualify";
  } else if (reviewTriggers.length > 0) {
    state = "needsReview";
  }
  const feeMath = calculateFees(input, state);
  return {
    state,
    blockers: blockers.slice(),
    reviewTriggers: reviewTriggers.slice(),
    timingNotices: timingNotices.slice(),
    appliedSuggestions: [],
    feeMath,
    primaryBlocker: blockers.length > 0 ? blockers[0] : void 0
  };
}
function calculateFees(input, state) {
  if (state === "qualifies" || state === "needsReview") {
    const appFee = FEE_MATH.lowImpact.application;
    const notifPerLoc = FEE_MATH.lowImpact.notificationPerLocation * input.locationCount;
    const lafdSpotCheck = FEE_MATH.lowImpact.lafdSpotCheck;
    const lowImpactTotal = appFee + notifPerLoc + lafdSpotCheck;
    const standardTotal2 = FEE_MATH.standard.application + FEE_MATH.standard.notificationPerLocation * input.locationCount + FEE_MATH.standard.lafdSpotCheck;
    const savings = standardTotal2 - lowImpactTotal;
    const savingsPercent = Math.round(savings / standardTotal2 * 100);
    return {
      applicationFee: appFee,
      notificationPerLocation: notifPerLoc,
      lafdSpotCheck,
      estimatedTotal: lowImpactTotal,
      savingsPercent,
      standardTierEstimate: standardTotal2
    };
  }
  const standardTotal = FEE_MATH.standard.application + FEE_MATH.standard.notificationPerLocation * input.locationCount + FEE_MATH.standard.lafdSpotCheck;
  return {
    applicationFee: FEE_MATH.standard.application,
    notificationPerLocation: FEE_MATH.standard.notificationPerLocation * input.locationCount,
    lafdSpotCheck: FEE_MATH.standard.lafdSpotCheck,
    estimatedTotal: standardTotal,
    savingsPercent: 0,
    standardTierEstimate: standardTotal
  };
}

// src/lib/mcp/tools/evaluate-low-impact-precheck.ts
var evaluate_low_impact_precheck_default = defineTool({
  name: "evaluate_low_impact_precheck",
  title: "Evaluate FilmLA Low Impact Pre-Check",
  description: "Run KAIRO's deterministic FilmLA Low Impact Permit Pilot Program pre-check. Given a planned City of Los Angeles shoot, returns whether it likely qualifies (qualifies / needsReview / doesNotQualify / notApplicable), all disqualifying blockers, review triggers, timing notices, and a Low-Impact vs Standard fee comparison. Sourced from the FilmLA KB \u2014 this is an estimate, not a permit approval.",
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  inputSchema: {
    firstFilmingDate: z.string().describe("First filming day, ISO date (YYYY-MM-DD)."),
    submissionDate: z.string().optional().describe("Application submission date, ISO date (YYYY-MM-DD). Defaults to today."),
    jurisdiction: z.enum(["cityOfLA", "other", "unsure", "notApplicable"]).optional().describe("Shoot jurisdiction. Low Impact only applies to City of LA."),
    locationCount: z.number().int().min(1).describe("Number of filming locations (parking/base camp don't count)."),
    consecutiveFilmingDays: z.number().int().min(1).describe("Consecutive filming days."),
    isConsecutiveDays: z.boolean().optional().describe("Whether the filming days are consecutive."),
    onSetCount: z.number().int().min(1).describe("Total cast & crew physically on set."),
    filmingOutsideBusinessHours: z.boolean().optional().describe("True if any filming happens outside 7am\u201310pm weekdays or 9am\u201310pm weekends."),
    hasSpecialEffects: z.boolean().optional(),
    hasGunfire: z.boolean().optional(),
    hasOfficerImpersonation: z.boolean().optional(),
    hasLaneClosures: z.boolean().optional(),
    hasTrafficControl: z.boolean().optional(),
    hasDrivingShots: z.boolean().optional(),
    hasAerialActivity: z.boolean().optional().describe("Drones, helicopters, planes."),
    hasAnimalActivity: z.boolean().optional(),
    hasAmplifiedMusic: z.boolean().optional(),
    hasLargeLighting: z.boolean().optional(),
    hasLargeLightingAssessment: z.enum(["yes", "no", "unsure"]).optional().describe("Self-assessment when hasLargeLighting is true."),
    hasGenerators: z.boolean().optional(),
    hasOpenFlames: z.boolean().optional(),
    hasPropaneHeaters: z.boolean().optional(),
    hasSmokeMachines: z.boolean().optional(),
    hasAlarmBypass: z.boolean().optional(),
    hasSmoking: z.boolean().optional(),
    hasPracticalStove: z.boolean().optional(),
    hasGrillingFoodPrep: z.boolean().optional(),
    hasStunts: z.boolean().optional(),
    locationTypes: z.array(z.string()).optional().describe(
      "Prohibited location type IDs present at the shoot. Any of: schools, city_buildings, neighborhood_conditions, rooftops, hotels, interior_business, airports, basements, multistory_apartments, high_rises, brush, harbor, helipads."
    ),
    isRecParkProperty: z.boolean().optional().describe("True if any location is on LA Rec & Parks property."),
    recParksActivities: z.array(z.string()).optional().describe("Rec & Parks-scoped activity rule IDs, only evaluated when isRecParkProperty is true."),
    projectName: z.string().optional().describe("Optional project label; not used in evaluation.")
  },
  handler: (input) => {
    const shoot = {
      projectName: input.projectName ?? "",
      jurisdiction: input.jurisdiction ?? "cityOfLA",
      firstFilmingDate: input.firstFilmingDate,
      submissionDate: input.submissionDate ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10),
      locationCount: input.locationCount,
      consecutiveFilmingDays: input.consecutiveFilmingDays,
      isConsecutiveDays: input.isConsecutiveDays,
      onSetCount: input.onSetCount,
      hasSpecialEffects: !!input.hasSpecialEffects,
      hasGunfire: !!input.hasGunfire,
      hasOfficerImpersonation: !!input.hasOfficerImpersonation,
      hasLaneClosures: !!input.hasLaneClosures,
      hasTrafficControl: !!input.hasTrafficControl,
      hasDrivingShots: !!input.hasDrivingShots,
      hasAerialActivity: !!input.hasAerialActivity,
      hasAnimalActivity: !!input.hasAnimalActivity,
      hasAmplifiedMusic: !!input.hasAmplifiedMusic,
      hasLargeLighting: !!input.hasLargeLighting,
      hasLargeLightingAssessment: input.hasLargeLightingAssessment,
      hasGenerators: !!input.hasGenerators,
      hasOpenFlames: !!input.hasOpenFlames,
      hasPropaneHeaters: !!input.hasPropaneHeaters,
      hasSmokeMachines: !!input.hasSmokeMachines,
      hasAlarmBypass: !!input.hasAlarmBypass,
      hasSmoking: !!input.hasSmoking,
      hasPracticalStove: !!input.hasPracticalStove,
      hasGrillingFoodPrep: !!input.hasGrillingFoodPrep,
      hasStunts: !!input.hasStunts,
      filmingOutsideBusinessHours: !!input.filmingOutsideBusinessHours,
      locationTypes: input.locationTypes ?? [],
      isRecParkProperty: !!input.isRecParkProperty,
      recParksActivities: input.recParksActivities ?? []
    };
    const result = evaluate(shoot);
    const summary = [
      `State: ${result.state}`,
      `Estimated Low Impact total: $${result.feeMath.estimatedTotal}`,
      `Standard tier estimate: $${result.feeMath.standardTierEstimate}`,
      result.feeMath.savingsPercent > 0 ? `Estimated savings: ${result.feeMath.savingsPercent}%` : null,
      result.blockers.length ? `Blockers: ${result.blockers.map((b) => b.label).join("; ")}` : null,
      result.reviewTriggers.length ? `Review triggers: ${result.reviewTriggers.map((r) => r.label).join("; ")}` : null,
      result.timingNotices.length ? `Timing notices: ${result.timingNotices.map((t) => t.label).join("; ")}` : null,
      "Estimate only \u2014 not a permit approval. See https://info.filmla.com/general-information/low-impact-permit-pilot-program."
    ].filter(Boolean).join("\n");
    return {
      content: [{ type: "text", text: summary }],
      structuredContent: { result }
    };
  }
});

// src/lib/mcp/tools/calculate-permit-fees.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";

// src/lib/feeCalculator.ts
import filmlaBaseFees from "npm:@/data/filmla-base-fees.json";
import jurisdictionsData from "npm:@/data/jurisdictions.json";
import activitiesData from "npm:@/data/activities.json";
import { FEE_MATH as FEE_MATH2 } from "npm:@/features/low-impact-precheck/rules";
var DEFAULT_INPUTS = {
  jurisdictionSlug: "",
  shootDays: 1,
  hoursPerDay: 12,
  crewSize: 20,
  isMotion: true,
  isStudent: false,
  isNonProfit: false,
  selectedActivities: [],
  isWeekend: false,
  isParksLocation: false,
  isBeachLocation: false,
  isBuildingLocation: false,
  isPortLocation: false,
  isDWPLocation: false,
  isFloodControlLocation: false,
  numberOfLocations: 1,
  numberOfParkingSpaces: 0,
  cateringCrewSize: 0,
  numberOfCars: 0,
  prepDays: 0,
  strikeDays: 0
};
function getJurisdiction(slug) {
  const jurisdictions = jurisdictionsData.jurisdictions;
  return Object.values(jurisdictions).find((j) => j.slug === slug) || null;
}
function getReqMeta(sourceFee) {
  return {
    requirementLevel: sourceFee?.requirement_level ?? "mandatory",
    requirementNote: sourceFee?.requirement_note ?? null
  };
}
function calculateFees2(inputs) {
  const jurisdiction = getJurisdiction(inputs.jurisdictionSlug);
  const lineItems = [];
  const warnings = [];
  let complexTimeline = false;
  let maxLeadDays = jurisdiction?.minLeadDaysStandard || 5;
  if (!jurisdiction) {
    return {
      jurisdiction: null,
      lineItems: [],
      subtotalFilmLA: 0,
      subtotalJurisdiction: 0,
      subtotalPersonnel: 0,
      subtotalLocation: 0,
      estimatedTotal: 0,
      warnings: ["Jurisdiction not found in database"],
      whatPeopleMiss: [],
      complexTimeline: false,
      estimatedLeadDays: 5
    };
  }
  const baseFees = filmlaBaseFees.fees;
  const lowImpact = !!inputs.lowImpactTier && inputs.jurisdictionSlug === "los-angeles" && inputs.isMotion && !inputs.isStudent && !inputs.isNonProfit;
  if (inputs.isStudent) {
    const isComplex = inputs.selectedActivities.length > 0;
    lineItems.push({
      id: "filmla_app",
      name: isComplex ? "Student Permit (Complex)" : "Student Permit (Simple)",
      amount: isComplex ? baseFees.student_permit_complex.rate : baseFees.student_permit_simple.rate,
      per: "permit",
      category: "filmla"
    });
  } else if (inputs.isNonProfit) {
    lineItems.push({
      id: "filmla_app",
      name: "Non-Profit (PSA) Permit App",
      amount: baseFees.nonprofit_psa_app.rate,
      per: "permit",
      category: "filmla"
    });
  } else if (inputs.isMotion) {
    if (lowImpact) {
      lineItems.push({
        id: "filmla_app",
        name: "Low Impact Permit Application",
        amount: FEE_MATH2.lowImpact.application,
        per: "permit",
        category: "filmla",
        note: "FilmLA Low Impact pilot \u2014 likely rate, pending FilmLA confirmation"
      });
    } else {
      lineItems.push({
        id: "filmla_app",
        name: "Permit Application Fee",
        amount: baseFees.permit_application.rate,
        per: "permit",
        category: "filmla",
        note: "Up to 5 locations, 7 consecutive days"
      });
    }
    if (inputs.shootDays > 7) {
      const extraRiders = Math.ceil((inputs.shootDays - 7) / 7);
      lineItems.push({
        id: "filmla_riders",
        name: `Permit Rider(s) \xC3\x97 ${extraRiders}`,
        amount: baseFees.permit_rider_business_hours.rate * extraRiders,
        per: "rider",
        category: "filmla",
        note: "Additional 7-day blocks"
      });
    }
    if (inputs.numberOfLocations > 5) {
      warnings.push(`Your ${inputs.numberOfLocations} locations exceed the base 5 included in the permit \xE2\x80\x94 additional rider fees may apply.`);
    }
  } else {
    if (inputs.crewSize >= 16) {
      lineItems.push({
        id: "filmla_app",
        name: "Still Photo App (Motion Rate \xE2\x80\x94 16+ crew)",
        amount: baseFees.permit_application.rate,
        per: "permit",
        category: "filmla",
        note: "Crew of 16+ requires Motion application fee"
      });
      warnings.push("Still photo crew of 16+ triggers Motion application rate ($931 instead of $104).");
    } else {
      lineItems.push({
        id: "filmla_app",
        name: "Still Photo Application Fee",
        amount: baseFees.still_photo_application.rate,
        per: "permit",
        category: "filmla"
      });
    }
  }
  if (lowImpact) {
    lineItems.push({
      id: "filmla_notification",
      name: "Notification Fee (Low Impact)",
      amount: FEE_MATH2.lowImpact.notificationPerLocation * inputs.numberOfLocations,
      per: `${inputs.numberOfLocations} filming location${inputs.numberOfLocations === 1 ? "" : "s"}`,
      category: "filmla",
      note: "Cast/crew parking & base camp locations are free"
    });
  } else {
    lineItems.push({
      id: "filmla_notification",
      name: "Notification Fee",
      amount: baseFees.notification_fee.rate * inputs.numberOfLocations,
      per: `notification radius (est. 1 per location \xD7 ${inputs.numberOfLocations})`,
      category: "filmla",
      note: "Billed per notification radius \u2014 typically one per filming location; locations sharing a radius may lower this.",
      isEstimate: inputs.numberOfLocations > 1
    });
  }
  for (const activityId of inputs.selectedActivities) {
    switch (activityId) {
      case "street_closure":
        lineItems.push({
          id: "filmla_lane_admin",
          name: "Lane Closure Administration",
          amount: baseFees.lane_closure_admin.rate * inputs.numberOfLocations,
          per: "involved location",
          category: "filmla"
        });
        complexTimeline = true;
        maxLeadDays = Math.max(maxLeadDays, jurisdiction.minLeadDaysComplex || 10);
        break;
      case "gunfire_sfx":
        lineItems.push({
          id: "filmla_gunfire_admin",
          name: "Gunfire Administration",
          amount: baseFees.gunfire_admin.rate * inputs.numberOfLocations,
          per: "involved location",
          category: "filmla"
        });
        complexTimeline = true;
        maxLeadDays = Math.max(maxLeadDays, jurisdiction.minLeadDaysComplex || 10);
        break;
      case "pyrotechnics":
        lineItems.push({
          id: "filmla_sfx_admin",
          name: "Special FX Administration",
          amount: baseFees.special_fx_admin.rate * inputs.numberOfLocations,
          per: "involved location",
          category: "filmla"
        });
        complexTimeline = true;
        maxLeadDays = Math.max(maxLeadDays, jurisdiction.minLeadDaysComplex || 10);
        break;
      case "drone_aerial":
        lineItems.push({
          id: "filmla_drone_admin",
          name: "Drone Administration",
          amount: baseFees.drone_admin.rate * inputs.numberOfLocations,
          per: "involved location",
          category: "filmla"
        });
        complexTimeline = true;
        maxLeadDays = Math.max(maxLeadDays, jurisdiction.minLeadDaysComplex || 10);
        break;
    }
  }
  const monitorLikely = inputs.selectedActivities.length > 0 || inputs.isParksLocation || inputs.isPortLocation || inputs.isBeachLocation || inputs.isFloodControlLocation;
  const monitorHours = inputs.hoursPerDay + 1;
  if (monitorLikely) lineItems.push({
    id: "filmla_monitor",
    name: "FilmLA Monitor",
    isEstimate: true,
    amount: baseFees.filmla_monitor.rate * monitorHours * inputs.shootDays,
    per: `${monitorHours}hrs \xC3\x97 ${inputs.shootDays} days`,
    category: "filmla",
    note: "Includes 1hr early arrival. Subject to OT/DT."
  });
  const jFees = jurisdiction.fees;
  if (inputs.jurisdictionSlug === "los-angeles") {
    if (inputs.crewSize >= 16) {
      if (lowImpact) {
        lineItems.push({
          id: "la_fire_spot_check",
          name: "LAFD Spot Check \u2014 Waived",
          amount: FEE_MATH2.lowImpact.lafdSpotCheck,
          per: "permit",
          category: "jurisdiction",
          department: "LA City Fire Department",
          note: "Waived under the Low Impact pilot"
        });
      } else {
        lineItems.push({
          id: "la_fire_spot_check",
          name: "LAFD Spot Check Surcharge",
          amount: jFees.fire_spot_check.rate,
          per: "permit",
          category: "jurisdiction",
          department: "LA City Fire Department",
          note: "Automatic for crews of 16+"
        });
      }
    }
    if (inputs.selectedActivities.includes("pyrotechnics") || inputs.selectedActivities.includes("gunfire_sfx")) {
      const fireHours = Math.max(jFees.fire_safety_officer.minimumHours, inputs.hoursPerDay) + jFees.fire_safety_officer.travelHours;
      lineItems.push({
        id: "la_fire_safety",
        name: "Fire Safety Officer",
        amount: jFees.fire_safety_officer.rate * fireHours * inputs.shootDays,
        per: `${fireHours}hrs \xC3\x97 ${inputs.shootDays} days`,
        category: "personnel",
        department: "LA City Fire Department",
        note: `${jFees.fire_safety_officer.minimumHours}hr min + 1hr travel`
      });
    }
    if (inputs.selectedActivities.includes("street_closure")) {
      lineItems.push({
        id: "la_lane_closure",
        name: "Lane & Street Closure Fee",
        amount: jFees.lane_street_closure.rate * inputs.numberOfLocations,
        per: "involved location",
        category: "jurisdiction",
        department: "LA City"
      });
      const lapdHours = Math.max(jFees.lapd_retired_off_duty.minimumHours || 8, inputs.hoursPerDay);
      lineItems.push({
        id: "la_lapd",
        name: "LAPD Officer (Retired/Off-Duty)",
        amount: (jFees.lapd_retired_off_duty.rateMin + jFees.lapd_retired_off_duty.rateMax) / 2 * lapdHours * inputs.shootDays,
        per: `~${lapdHours}hrs \xD7 ${inputs.shootDays} days`,
        category: "personnel",
        department: "LAPD",
        note: `8hr minimum. Paid directly to provider`,
        isEstimate: true,
        paidDirectly: true,
        rateLow: jFees.lapd_retired_off_duty.rateMin * lapdHours * inputs.shootDays,
        rateHigh: jFees.lapd_retired_off_duty.rateMax * lapdHours * inputs.shootDays
      });
    }
    if (inputs.isParksLocation) {
      lineItems.push({
        id: "la_parks_use",
        name: "Rec & Parks \xE2\x80\x94 Film Use",
        amount: jFees.rec_parks_film_use.rate * inputs.shootDays,
        per: `${inputs.shootDays} days`,
        category: "location",
        department: "LA Dept of Rec & Parks"
      });
      if (inputs.prepDays > 0) {
        lineItems.push({
          id: "la_parks_prep",
          name: "Rec & Parks \xE2\x80\x94 Prep/Strike",
          amount: jFees.rec_parks_prep_strike.rate * (inputs.prepDays + inputs.strikeDays),
          per: `${inputs.prepDays + inputs.strikeDays} days`,
          category: "location",
          department: "LA Dept of Rec & Parks"
        });
      }
      lineItems.push({
        id: "la_parks_monitor",
        name: "Rec & Parks Monitor",
        amount: jFees.rec_parks_monitor.rate * (inputs.hoursPerDay + 1) * inputs.shootDays,
        per: "hour",
        category: "personnel",
        department: "LA Dept of Rec & Parks"
      });
      lineItems.push({
        id: "la_parks_monitor_reporting",
        name: "Rec & Parks Monitor Reporting",
        amount: jFees.rec_parks_monitor_reporting.rate * inputs.shootDays,
        per: "shift",
        category: "personnel",
        department: "LA Dept of Rec & Parks"
      });
    }
    if (inputs.isPortLocation) {
      lineItems.push({
        id: "la_port_use",
        name: "Port of LA \xE2\x80\x94 Use Fee",
        amount: jFees.port_use_fee.rate * inputs.shootDays,
        per: `${inputs.shootDays} days`,
        category: "location",
        department: "Port of Los Angeles"
      });
    }
  }
  if (inputs.jurisdictionSlug === "los-angeles-county") {
    if (inputs.isMotion) {
      lineItems.push({
        id: "lac_fire_review",
        name: "County Fire \xE2\x80\x94 Filming Review",
        amount: jFees.fire_filming_review.rate,
        per: "permit",
        category: "jurisdiction",
        department: "LA County Fire"
      });
    } else if (inputs.crewSize >= 16) {
      lineItems.push({
        id: "lac_fire_review",
        name: "County Fire \xE2\x80\x94 Still Photo Review",
        amount: jFees.fire_still_photo_review.rate,
        per: "permit",
        category: "jurisdiction",
        department: "LA County Fire",
        note: "16+ People"
      });
    }
    if (inputs.selectedActivities.includes("pyrotechnics") || inputs.selectedActivities.includes("gunfire_sfx")) {
      lineItems.push({
        id: "lac_sfx_permit",
        name: "County Fire \xE2\x80\x94 Special Effects Permit",
        amount: jFees.fire_special_effects_permit.rate * inputs.numberOfLocations,
        per: "involved location",
        category: "jurisdiction",
        department: "LA County Fire"
      });
      const fsoHours = Math.max(jFees.fire_safety_officer.minimumHours, inputs.hoursPerDay);
      lineItems.push({
        id: "lac_fso",
        name: "County Fire Safety Officer",
        amount: jFees.fire_safety_officer.rate * fsoHours * inputs.shootDays,
        per: `${fsoHours}hrs \xC3\x97 ${inputs.shootDays} days`,
        category: "personnel",
        department: "LA County Fire",
        note: "4hr min, Flat Rate (No OT/DT). Paid directly to provider",
        paidDirectly: true
      });
    }
    if (inputs.selectedActivities.includes("street_closure")) {
      lineItems.push({
        id: "lac_roads_inspection",
        name: "County Roads \xE2\x80\x94 Inspection/Use",
        amount: jFees.roads_inspection_use.rate * inputs.shootDays,
        per: `${inputs.shootDays} days`,
        category: "jurisdiction",
        department: "LA County Roads"
      });
      lineItems.push({
        id: "lac_roads_encroachment",
        name: "County Roads \xE2\x80\x94 Encroachment Processing",
        amount: jFees.roads_encroachment_processing.rate,
        per: "area",
        category: "jurisdiction",
        department: "LA County Roads"
      });
      lineItems.push({
        id: "lac_roads_app",
        name: "County Roads \xE2\x80\x94 Application/Issuance",
        amount: jFees.roads_application_issuance.rate * inputs.numberOfLocations,
        per: "involved location",
        category: "jurisdiction",
        department: "LA County Roads"
      });
      const sheriffHours = Math.max(jFees.sheriff_officer.minimumHours, inputs.hoursPerDay);
      lineItems.push({
        id: "lac_sheriff",
        name: "County Sheriff Officer",
        amount: jFees.sheriff_officer.rate * sheriffHours * inputs.shootDays,
        per: `${sheriffHours}hrs \xC3\x97 ${inputs.shootDays} days`,
        category: "personnel",
        department: "LA County Sheriff",
        note: "6hr min, Flat Rate + $1.22/mile mileage. Paid directly to provider",
        paidDirectly: true,
        isEstimate: true
      });
    }
    if (inputs.isBeachLocation) {
      lineItems.push({
        id: "lac_beach_use",
        name: "County Beaches \xE2\x80\x94 Filming Use",
        amount: jFees.beaches_filming_use.rate * inputs.shootDays,
        per: `${inputs.shootDays} days`,
        category: "location",
        department: "LA County Beaches"
      });
      if (inputs.prepDays > 0 || inputs.strikeDays > 0) {
        const totalPrepStrike = inputs.prepDays + inputs.strikeDays;
        const basicDays = Math.min(totalPrepStrike, 3);
        const extendedDays = Math.max(0, totalPrepStrike - 3);
        let prepCost = basicDays * jFees.beaches_prep_strike.rate;
        if (extendedDays > 0) {
          prepCost += extendedDays * jFees.beaches_prep_strike_extended.rate;
        }
        lineItems.push({
          id: "lac_beach_prep",
          name: "County Beaches \xE2\x80\x94 Prep/Strike",
          amount: prepCost,
          per: `${totalPrepStrike} days`,
          category: "location",
          department: "LA County Beaches",
          note: extendedDays > 0 ? `$100/day first 3 days, $400/day after` : void 0
        });
      }
    }
    if (inputs.isParksLocation) {
      lineItems.push({
        id: "lac_parks_use",
        name: "County Parks \xE2\x80\x94 Filming Use",
        amount: jFees.parks_filming_use.rate * inputs.shootDays,
        per: `${inputs.shootDays} days`,
        category: "location",
        department: "LA County Parks"
      });
    }
    if (inputs.isFloodControlLocation) {
      lineItems.push({
        id: "lac_flood_permit",
        name: "Flood Control \xE2\x80\x94 Permit Issuance",
        amount: jFees.flood_control_permit.rate,
        per: "permit",
        category: "jurisdiction",
        department: "LA County Flood Control"
      });
      const totalFloodDays = inputs.shootDays + inputs.prepDays + inputs.strikeDays;
      lineItems.push({
        id: "lac_flood_use",
        name: "Flood Control \xE2\x80\x94 Use Fee",
        amount: jFees.flood_control_use.rate * totalFloodDays,
        per: `${totalFloodDays} days (all activity days)`,
        category: "location",
        department: "LA County Flood Control",
        note: "Applies to ALL prep, strike, still photo & filming days"
      });
      warnings.push(`Flood control locations are $${jFees.flood_control_use.rate.toLocaleString()}/day \xE2\x80\x94 one of the highest daily rates in LA County.`);
    }
  }
  if (inputs.jurisdictionSlug === "culver-city") {
    lineItems.push({
      id: "cc_application",
      name: "Culver City Application Fee",
      amount: jFees.city_application.rate,
      per: "permit",
      category: "jurisdiction",
      department: "Culver City",
      note: "In addition to FilmLA application fee"
    });
    if (inputs.isMotion) {
      lineItems.push({
        id: "cc_daily_use",
        name: "Culver City Filming Daily Use",
        amount: jFees.filming_daily_use.rate * inputs.shootDays,
        per: `${inputs.shootDays} days`,
        category: "jurisdiction",
        department: "Culver City"
      });
    } else {
      lineItems.push({
        id: "cc_daily_use",
        name: "Culver City Still Photo Daily Use",
        amount: jFees.still_photo_daily_use.rate * inputs.shootDays,
        per: `${inputs.shootDays} days`,
        category: "jurisdiction",
        department: "Culver City"
      });
    }
    lineItems.push({
      id: "cc_fire_spot",
      name: "Culver City Fire Spot Check",
      amount: jFees.fire_spot_check.rate * inputs.numberOfLocations,
      per: "involved location",
      category: "jurisdiction",
      department: "Culver City Fire Department"
    });
    if (inputs.selectedActivities.includes("street_closure")) {
      if (inputs.isWeekend) {
        lineItems.push({
          id: "cc_police",
          name: "Culver City Police Officer (Weekend/Holiday)",
          amount: jFees.police_officer_weekend_holiday.rate * inputs.shootDays,
          per: `${inputs.shootDays} days`,
          category: "personnel",
          department: "Culver City Police"
        });
      } else {
        const basePolice = jFees.police_officer_weekday.rate;
        const extraHours = Math.max(0, inputs.hoursPerDay - 8);
        const extraCost = extraHours * jFees.police_officer_additional_hours.rate;
        lineItems.push({
          id: "cc_police",
          name: "Culver City Police Officer (Weekday)",
          amount: (basePolice + extraCost) * inputs.shootDays,
          per: `${inputs.shootDays} days`,
          category: "personnel",
          department: "Culver City Police",
          note: "8hr minimum included"
        });
      }
    }
    if (inputs.selectedActivities.includes("pyrotechnics") || inputs.selectedActivities.includes("gunfire_sfx")) {
      if (inputs.isWeekend) {
        lineItems.push({
          id: "cc_fire_officer",
          name: "Culver City Fire Officer (Weekend/Holiday)",
          amount: jFees.fire_officer_weekend_holiday.rate * inputs.shootDays,
          per: `${inputs.shootDays} days`,
          category: "personnel",
          department: "Culver City Fire"
        });
      } else {
        const baseFire = jFees.fire_officer_weekday.rate;
        const extraFireHours = Math.max(0, inputs.hoursPerDay - 8);
        const extraFireCost = extraFireHours * jFees.fire_officer_additional_hours.rate;
        lineItems.push({
          id: "cc_fire_officer",
          name: "Culver City Fire Officer (Weekday)",
          amount: (baseFire + extraFireCost) * inputs.shootDays,
          per: `${inputs.shootDays} days`,
          category: "personnel",
          department: "Culver City Fire",
          note: "8hr minimum included"
        });
      }
    }
    if (inputs.numberOfParkingSpaces > 0) {
      lineItems.push({
        id: "cc_posting",
        name: "Parking Posting (Non-Metered)",
        amount: jFees.posting_non_metered.rate * inputs.numberOfParkingSpaces * inputs.shootDays,
        per: `${inputs.numberOfParkingSpaces} spaces \xC3\x97 ${inputs.shootDays} days`,
        category: "jurisdiction",
        department: "Culver City",
        note: "Using non-metered rate \xE2\x80\x94 downtown/metered rates higher"
      });
    }
  }
  const filmlaReqMap = {
    filmla_app: inputs.isStudent ? inputs.selectedActivities.length > 0 ? baseFees.student_permit_complex : baseFees.student_permit_simple : inputs.isNonProfit ? baseFees.nonprofit_psa_app : inputs.isMotion ? baseFees.permit_application : inputs.crewSize >= 16 ? baseFees.permit_application : baseFees.still_photo_application,
    filmla_riders: baseFees.permit_rider_business_hours,
    filmla_notification: baseFees.notification_fee,
    filmla_lane_admin: baseFees.lane_closure_admin,
    filmla_gunfire_admin: baseFees.gunfire_admin,
    filmla_sfx_admin: baseFees.special_fx_admin,
    filmla_drone_admin: baseFees.drone_admin,
    filmla_monitor: baseFees.filmla_monitor
  };
  const jReqMap = jFees ? {
    la_fire_spot_check: jFees.fire_spot_check,
    la_fire_safety: jFees.fire_safety_officer,
    la_lane_closure: jFees.lane_street_closure,
    la_lapd: jFees.lapd_retired_off_duty,
    la_parks_use: jFees.rec_parks_film_use,
    la_parks_prep: jFees.rec_parks_prep_strike,
    la_parks_monitor: jFees.rec_parks_monitor,
    la_parks_monitor_reporting: jFees.rec_parks_monitor_reporting,
    la_port_use: jFees.port_use_fee,
    lac_fire_review: jFees.fire_filming_review || jFees.fire_still_photo_review,
    lac_sfx_permit: jFees.fire_special_effects_permit,
    lac_fso: jFees.fire_safety_officer,
    lac_roads_inspection: jFees.roads_inspection_use,
    lac_roads_encroachment: jFees.roads_encroachment_processing,
    lac_roads_app: jFees.roads_application_issuance,
    lac_sheriff: jFees.sheriff_officer,
    lac_beach_use: jFees.beaches_filming_use,
    lac_beach_prep: jFees.beaches_prep_strike,
    lac_parks_use: jFees.parks_filming_use,
    lac_flood_permit: jFees.flood_control_permit,
    lac_flood_use: jFees.flood_control_use,
    cc_application: jFees.city_application,
    cc_daily_use: jFees.filming_daily_use || jFees.still_photo_daily_use,
    cc_fire_spot: jFees.fire_spot_check,
    cc_police: jFees.police_officer_weekday || jFees.police_officer_weekend_holiday,
    cc_fire_officer: jFees.fire_officer_weekday || jFees.fire_officer_weekend_holiday,
    cc_posting: jFees.posting_non_metered
  } : {};
  const allReqMap = { ...filmlaReqMap, ...jReqMap };
  for (const item of lineItems) {
    const src = allReqMap[item.id];
    if (src && !item.requirementLevel) {
      const meta = getReqMeta(src);
      item.requirementLevel = meta.requirementLevel;
      item.requirementNote = meta.requirementNote;
    }
    if (!item.requirementLevel) {
      item.requirementLevel = "mandatory";
    }
  }
  const subtotalFilmLA = lineItems.filter((i) => i.category === "filmla").reduce((sum, i) => sum + i.amount, 0);
  const subtotalJurisdiction = lineItems.filter((i) => i.category === "jurisdiction").reduce((sum, i) => sum + i.amount, 0);
  const subtotalPersonnel = lineItems.filter((i) => i.category === "personnel").reduce((sum, i) => sum + i.amount, 0);
  const subtotalLocation = lineItems.filter((i) => i.category === "location").reduce((sum, i) => sum + i.amount, 0);
  const estimatedTotal = subtotalFilmLA + subtotalJurisdiction + subtotalPersonnel + subtotalLocation;
  for (const actId of inputs.selectedActivities) {
    const activity = activitiesData.activities.find((a) => a.id === actId);
    if (activity) {
      if (activity.triggersComplexTimeline) complexTimeline = true;
      maxLeadDays = Math.max(maxLeadDays, (jurisdiction.minLeadDaysStandard || 5) + (activity.additionalLeadDays || 0));
    }
  }
  return {
    jurisdiction,
    lineItems,
    subtotalFilmLA,
    subtotalJurisdiction,
    subtotalPersonnel,
    subtotalLocation,
    estimatedTotal,
    warnings,
    whatPeopleMiss: jurisdiction.whatPeopleMiss || [],
    complexTimeline,
    estimatedLeadDays: maxLeadDays
  };
}

// src/lib/mcp/tools/calculate-permit-fees.ts
var calculate_permit_fees_default = defineTool2({
  name: "calculate_permit_fees",
  title: "Calculate film permit fees",
  description: "Estimate itemized film permit fees for a planned shoot in a supported jurisdiction (e.g. City of Los Angeles, LA County). Combines FilmLA base fees with jurisdiction-specific personnel and location surcharges. Returns line items, subtotals, an estimated total, warnings, and estimated lead time. Optionally applies FilmLA Low Impact pilot pricing (LA City motion only). Estimate only \u2014 not a quote.",
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  inputSchema: {
    jurisdictionSlug: z2.string().describe("Jurisdiction slug, e.g. 'los-angeles', 'los-angeles-county'."),
    shootDays: z2.number().int().min(1).describe("Number of shoot days."),
    hoursPerDay: z2.number().min(1).max(24).describe("Hours per shoot day."),
    crewSize: z2.number().int().min(1).describe("Crew size."),
    isMotion: z2.boolean().describe("True for motion filming, false for still photo."),
    isStudent: z2.boolean().optional(),
    isNonProfit: z2.boolean().optional(),
    selectedActivities: z2.array(z2.string()).optional().describe("Activity IDs, e.g. street_closure, gunfire_sfx, pyrotechnics, drone_aerial."),
    isWeekend: z2.boolean().optional(),
    isParksLocation: z2.boolean().optional(),
    isBeachLocation: z2.boolean().optional(),
    isBuildingLocation: z2.boolean().optional(),
    isPortLocation: z2.boolean().optional(),
    isDWPLocation: z2.boolean().optional(),
    isFloodControlLocation: z2.boolean().optional(),
    numberOfLocations: z2.number().int().min(1).optional(),
    numberOfParkingSpaces: z2.number().int().min(0).optional(),
    cateringCrewSize: z2.number().int().min(0).optional(),
    numberOfCars: z2.number().int().min(0).optional(),
    prepDays: z2.number().int().min(0).optional(),
    strikeDays: z2.number().int().min(0).optional(),
    lowImpactTier: z2.boolean().optional().describe(
      "Apply FilmLA Low Impact pilot pricing. Only affects LA City motion, non-student, non-profit shoots; ignored otherwise. Confirm eligibility with evaluate_low_impact_precheck first."
    )
  },
  handler: (input) => {
    const inputs = {
      ...DEFAULT_INPUTS,
      ...input,
      isStudent: !!input.isStudent,
      isNonProfit: !!input.isNonProfit,
      selectedActivities: input.selectedActivities ?? [],
      isWeekend: !!input.isWeekend,
      isParksLocation: !!input.isParksLocation,
      isBeachLocation: !!input.isBeachLocation,
      isBuildingLocation: !!input.isBuildingLocation,
      isPortLocation: !!input.isPortLocation,
      isDWPLocation: !!input.isDWPLocation,
      isFloodControlLocation: !!input.isFloodControlLocation,
      numberOfLocations: input.numberOfLocations ?? 1,
      numberOfParkingSpaces: input.numberOfParkingSpaces ?? 0,
      cateringCrewSize: input.cateringCrewSize ?? 0,
      numberOfCars: input.numberOfCars ?? 0,
      prepDays: input.prepDays ?? 0,
      strikeDays: input.strikeDays ?? 0
    };
    const result = calculateFees2(inputs);
    const lines = result.lineItems.map(
      (li) => `- ${li.name}: $${Math.round(li.amount)}${li.isEstimate ? " (est.)" : ""}${li.note ? ` \u2014 ${li.note}` : ""}`
    );
    const text = [
      `Jurisdiction: ${result.jurisdiction?.name ?? inputs.jurisdictionSlug}`,
      `Estimated total: $${Math.round(result.estimatedTotal)}`,
      `Estimated lead time: ${result.estimatedLeadDays} days${result.complexTimeline ? " (complex)" : ""}`,
      "",
      "Line items:",
      ...lines,
      result.warnings.length ? `
Warnings:
${result.warnings.map((w) => `- ${w}`).join("\n")}` : "",
      "\nEstimate only \u2014 not a quote. Cross-check with FilmLA before submitting."
    ].filter(Boolean).join("\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: { result }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "kairo-mcp",
  title: "KAIRO \u2014 Film Permit Intelligence",
  version: "0.1.0",
  instructions: "Tools for planning City of Los Angeles (and LA County) film permits. Use `evaluate_low_impact_precheck` to check whether a shoot likely qualifies for FilmLA's Low Impact Permit Pilot Program and see the fee comparison. Use `calculate_permit_fees` to itemize base FilmLA and jurisdiction-specific fees for a planned shoot. All outputs are deterministic estimates sourced from public FilmLA rules \u2014 not permit approvals or binding quotes.",
  tools: [evaluate_low_impact_precheck_default, calculate_permit_fees_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
