// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehxaweuopfqcxubryiju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoeGF3ZXVvcGZxY3h1YnJ5aWp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4NTE3MzgsImV4cCI6MjA4NjQyNzczOH0.VKcV2hKPorHYFKEEpL5q-C3BIWHwHoJuRPIHmFECQ2k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});